import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faHouse,
  faBars,
  faBell,
  faMagnifyingGlass,
  faStar as fasStar,
  faArrowLeft,
  faVideo,
  faUsers,
  faShop,
  faUtensils,
  faShieldAlt,
  faChevronRight,
  faShieldHalved,
  faAngleRight,
  faChevronDown,
  faChevronUp,
  faCheck,
  faKey,
  faDeleteLeft,
  faUserPen,
  faCamera,
  faTriangleExclamation,
  faCircleInfo,
  faMotorcycle,
  faFirstAid,
  faHeart,
  faCross,
  faLocationDot,
  faBuilding,
  faClipboard,
  faChartBar,
} from "@fortawesome/free-solid-svg-icons";
import {
  faMap,
  faStar as farStar,
  faCircleXmark,
  faFileLines,
  faEnvelope,
  faUser,
} from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faHouse,
  faMap,
  fasStar,
  faBars,
  faBell,
  faMagnifyingGlass,
  faCircleXmark,
  farStar,
  faArrowLeft,
  faVideo,
  faUsers,
  faShop,
  faUtensils,
  faShieldHalved,
  faAngleRight,
  faShieldAlt,
  faChevronRight,
  faFileLines,
  faEnvelope,
  faUser,
  faChevronDown,
  faChevronUp,
  faCheck,
  faKey,
  faDeleteLeft,
  faUserPen,
  faCamera,
  faTriangleExclamation,
  faCircleInfo,
  faMotorcycle,
  faHeart,
  faFirstAid,
  faCross,
  faLocationDot,
  faBuilding,
  faClipboard,
  faChartBar,
);

export { FontAwesomeIcon };
